{
 "title": "Pizza Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Pizza creation Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "latency_pizza_creation_milliseconds",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "latency_all_endpoints_milliseconds",
     "legendFormat": "All Endpoints"
    }
   ]
  },
  {
   "title": "Pizza Revenue per Minute",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(pizza_revenue_dollars[1m])",
     "legendFormat": "Revenue/Min"
    }
   ]
  },
  {
   "title": "Pizza Sold",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    { "expr": "rate(http_requests_total[1m])", "legendFormat": "pizza purchases" },
    { "expr": "pizza_creation_failures", "legendFormat": "creation Failure" }
   ]
  },
  {
   "title": "System Resources (CPU & Memory)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "system_cpu_usage_percent", "legendFormat": "__auto" },
    { "expr": "system_memory_usage_percent", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Authentication Attempts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "targets": [
    {
     "expr": "rate(auth_attempts_successful[1m]) ",
     "legendFormat": "success"
    },
    { "expr": "rate(auth_attempts_failed[1m])", "legendFormat": "fail" }
   ]
  },
  {
   "title": "Active Users",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
   "targets": [
    { "expr": "active_users", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total HTTP Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "rate(http_requests_total[1m])", "legendFormat": "all" },
    { "expr": "rate(http_requests_get[1m])", "legendFormat": "get" },
    { "expr": "rate(http_requests_post[1m])", "legendFormat": "post" },
    { "expr": "rate(http_requests_put[1m]) ", "legendFormat": "put" },
    { "expr": "rate(http_requests_delete[1m])", "legendFormat": "delete" }
   ]
  }
 ]
}